#!/usr/bin/env python

import sys
import os
import traceback
import logging
import shutil
from PySide6.QtCore import QCoreApplication
from PySide6.QtDBus import QDBusConnection, QDBusInterface

from onedrive.gui import run

from onedrive.config import OnedriveConfig


def main():
    if len(sys.argv) >= 2 and sys.argv[1].startswith("onedrive://"):
        try:
            _ = QCoreApplication()
            sb = QDBusConnection.sessionBus()
            if not sb.isConnected():
                print("Session d-bus not available", file=sys.stderr)
                sys.exit(1)
            oauth = QDBusInterface('org.python.onedrive', '/oauth', '', sb)
            if not oauth.isValid():
                print("Unable to connect to onedrive d-bus:", file=sys.stderr)
                print(sb.lastError().message(), file=sys.stderr)
                sys.exit(1)
            r = oauth.call('callback', sys.argv[1])
            if not r.isValid():
                print("Error while sending URL to onedrive d-bus:\n", file=sys.stderr)
                print(r.errorMessage(), file=sys.stderr)
                sys.exit(1)
            sys.exit(0)
        except Exception:
            print("Unable to send onedrive URL to main client :\n", file=sys.stderr)
            traceback.print_exc()
            sys.exit(1)
    else:
        try:
            user_conf = os.path.join(os.getenv("HOME"), ".config", "onedrive")
            if len(sys.argv) >= 2:
                config = OnedriveConfig(sys.argv[1])
            else:
                config = OnedriveConfig(user_conf)
        except:
            print("Unable to configure onedrive client :\n", file=sys.stderr)
            traceback.print_exc()
            sys.exit(1)

        logging.info("Starting Onedrive GUI")
        run(config)


if __name__ == '__main__':
    main()
