#!/usr/bin/env python

import sys
import traceback


def main():
    if len(sys.argv) >= 2 and sys.argv[1].startswith("onedrive://"):
        from PySide6.QtCore import QCoreApplication
        from PySide6.QtDBus import QDBusConnection, QDBusInterface, QDBusMessage

        with open('/tmp/redir.log', 'w') as l:
            try:
                _ = QCoreApplication()
                sb = QDBusConnection.sessionBus()
                if not sb.isConnected():
                    print("Session d-bus not available", file=l)
                    sys.exit(1)
                oauth = QDBusInterface('org.python.onedrive', '/', '', sb)
                if not oauth.isValid():
                    print("Unable to connect to onedrive d-bus:", end='', file=l)
                    print(sb.lastError().message(), file=l)
                    sys.exit(1)
                r = oauth.call('oauth', sys.argv[1])
                if r.type() != QDBusMessage.MessageType.ReplyMessage:
                    print("Error while sending URL to onedrive d-bus:\n", file=l)
                    if r.type() == QDBusMessage.MessageType.ErrorMessage:
                        print(r.errorMessage(), file=l)
                    else:
                        print("Unexpected Type "+str(r.type())+" received !")
                    sys.exit(1)
                sys.exit(0)
            except Exception:
                print("Unable to send onedrive URL to main client :\n", file=l)
                traceback.print_exc(file=l)
                sys.exit(1)
    else:
        from onedrive.gui import run
        from onedrive.config import OnedriveConfig
        import os
        import logging

        try:
            user_conf = os.path.join(os.getenv("HOME"), ".config", "onedrive")
            if len(sys.argv) >= 2:
                config = OnedriveConfig(sys.argv[1])
            else:
                config = OnedriveConfig(user_conf)
        except:
            print("Unable to configure onedrive client :\n", file=sys.stderr)
            traceback.print_exc()
            sys.exit(1)

        logging.info("Starting Onedrive GUI")
        run(config)


if __name__ == '__main__':
    main()
